import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {chromium,expect} from '@playwright/test';
const root=resolve(import.meta.dirname,'..'),shots=join(root,'test-results','pages');
await mkdir(shots,{recursive:true});
const preview=spawn(process.execPath,['scripts/preview-workbench.mjs'],{cwd:root,stdio:['ignore','pipe','pipe']});
let browser,page;
try{
 const {url}=await new Promise((resolve,reject)=>{let output='',errors='';const timeout=setTimeout(()=>reject(new Error(errors||'Preview timeout')),20000);preview.stderr.on('data',v=>errors+=v);preview.once('exit',code=>{clearTimeout(timeout);reject(new Error('Preview exited '+code+errors));});preview.stdout.on('data',v=>{output+=v;const line=output.split('\n').find(v=>v.startsWith('{'));if(line){clearTimeout(timeout);resolve(JSON.parse(line));}});});
 const call=async(action,args={})=>{const r=await fetch(new URL('/dispatch',url),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,args})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;};
 const novelId=(await call('novel.list'))[0].id,chapter=(await call('chapter.list',{novelId}))[0];
 const prose=Array.from({length:90},(_,i)=>`第${i+1}段。${'雨停之后，街上的行人渐渐多了起来，她收好那封旧信。'.repeat(3)}`).join('\n\n');
 await call('chapter.update',{novelId,chapterId:chapter.id,expectedRevision:chapter.revision,content:prose});
 await call('planning.apply',{novelId,requestId:crypto.randomUUID(),operations:[{op:'node.create',value:{title:'原有主线',content:'原有主线正文'}}]});
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});page=await browser.newPage({viewport:{width:1100,height:900},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('.chapter-item').first().click();
 const manuscript=page.getByLabel('正文',{exact:true}),scroll=page.locator('.editor-scroll');
 await expect(manuscript).toHaveValue(prose);await expect(page.getByRole('button',{name:'阅读',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'编辑',exact:true})).toHaveCount(0);
 await scroll.evaluate(el=>el.scrollTop=1000);const before=await scroll.evaluate(el=>el.scrollTop);
 await manuscript.evaluate(el=>{el.focus({preventScroll:true});el.setSelectionRange(1000,1000);});await page.keyboard.insertText('新的讨论');
 await expect.poll(async()=>(await call('chapter.get',{novelId,chapterId:chapter.id,maxChars:200000})).content.includes('新的讨论')).toBe(true);
 expect(await scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(700);
 // A clean remote sync and autosave do not replace the editing surface or reset scroll.
 const updated=await call('chapter.get',{novelId,chapterId:chapter.id,maxChars:200000});
 await call('chapter.update',{novelId,chapterId:chapter.id,expectedRevision:updated.revision,append:'\n\n后续段落。'});
 await expect(manuscript).toHaveValue(/后续段落。$/,{timeout:10000});expect(await scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(700);
 await page.screenshot({path:join(shots,'unified-manuscript.png')});
 await page.getByRole('button',{name:'规划',exact:true}).click();await expect(page.locator('.planning-card')).toHaveCount(1);
 await page.getByRole('button',{name:'＋ 页面',exact:true}).click();const pageDialog=page.getByRole('dialog',{name:'新建规划页面',exact:true});
 await pageDialog.getByLabel('页面名称').fill('港口篇');await pageDialog.getByLabel('用途摘要').fill('与当前主线独立的新情节');await pageDialog.getByRole('button',{name:'保存页面',exact:true}).click();
 await expect(page.getByRole('navigation',{name:'规划页面'}).getByRole('button',{name:/港口篇/})).toHaveAttribute('aria-current','page');await expect(page.locator('.planning-card')).toHaveCount(0);
 const pageId=(await call('planning.pages',{novelId})).find(p=>p.name==='港口篇').id;
 const canvas=page.locator('.planning-canvas-scroll');
 const context=async(x=80,y=85)=>{await canvas.click({button:'right',position:{x,y}});await expect(page.getByRole('menu',{name:'画布操作'})).toBeVisible();};
 await context();await page.getByRole('menuitem',{name:'新建情节',exact:true}).click();await page.locator('.creation').getByLabel('标题',{exact:true}).fill('抵达港口');await page.locator('.creation').getByLabel('正文',{exact:false}).fill('独立新情节');await page.locator('.creation').getByRole('button',{name:'创建',exact:true}).click();await page.getByRole('button',{name:'‹ 返回规划'}).click();
 await expect(page.locator('.planning-card')).toHaveCount(1);await expect(page.locator('.planning-card')).toContainText('抵达港口');
 const scene=(await call('planning.list',{novelId,pageId})).items[0];expect(scene.position.x).toBeGreaterThanOrEqual(32);expect((await call('planning.list',{novelId,pageId:null})).total).toBe(1);
 await context(400,80);await page.getByRole('menuitem',{name:'文字批注',exact:true}).click();let dialog=page.getByRole('dialog',{name:'文字批注',exact:true});
 await dialog.getByLabel('标题',{exact:true}).fill('待讨论的动机');await dialog.getByLabel('批注内容').fill('人物主动赴约，还是受到威胁？\n这是一条待讨论的问题。');await dialog.getByLabel('底色').selectOption('sky');await dialog.getByLabel('字体',{exact:true}).selectOption('serif');await dialog.getByLabel('字号',{exact:true}).selectOption('24');await dialog.getByRole('button',{name:'保存批注'}).click();
 await expect(page.locator('.decoration-note')).toContainText('待讨论的动机');await expect(page.locator('.decoration-note')).toHaveCSS('font-size','24px');
 const note=(await call('planning.decorations',{novelId,pageId})).items[0];
 const drag=async locator=>{await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+40,b.y+b.height/2+50,{steps:5});await page.mouse.up();};
 await drag(page.locator('.decoration-note header'));
 await expect.poll(async()=>(await call('planning.decorations',{novelId,pageId})).items.find(d=>d.id===note.id).position.y).toBe(note.position.y+50);await expect(page.getByRole('dialog')).toHaveCount(0);
 await context(70,320);await page.getByRole('menuitem',{name:'背景框',exact:true}).click();dialog=page.getByRole('dialog',{name:'背景框',exact:true});await dialog.getByLabel('标题',{exact:true}).fill('港口讨论区域');await dialog.getByLabel('批注内容').fill('先理清动机，再考虑冲突');await dialog.getByLabel('底色').selectOption('sage');await dialog.getByRole('button',{name:'保存批注'}).click();await expect(page.locator('.decoration-frame')).toHaveCount(1);
 let frame=(await call('planning.decorations',{novelId,pageId})).items.find(d=>d.kind==='frame');
 await drag(page.getByRole('button',{name:'调整批注尺寸 港口讨论区域',exact:true}));
 await expect.poll(async()=>(await call('planning.decorations',{novelId,pageId})).items.find(d=>d.id===frame.id).width).toBe(frame.width+40);
 await page.screenshot({path:join(shots,'planning-page-wide.png')});
 // Existing main page never receives either the new scene or visual annotations.
 await page.getByRole('navigation',{name:'规划页面'}).getByRole('button',{name:/主线规划/}).click();await expect(page.locator('.planning-card')).toContainText('原有主线');await expect(page.locator('.planning-decoration')).toHaveCount(0);
 await page.getByRole('navigation',{name:'规划页面'}).getByRole('button',{name:/港口篇/}).click();await expect(page.locator('.planning-decoration')).toHaveCount(2);
 await page.reload();await page.getByRole('button',{name:'规划',exact:true}).click();await expect(page.locator('.planning-card')).toContainText('抵达港口');await expect(page.locator('.planning-decoration')).toHaveCount(2);
 await page.getByRole('button',{name:'页面设置',exact:true}).click();dialog=page.getByRole('dialog',{name:'页面设置',exact:true});await expect(dialog.getByRole('button',{name:'删除空页面'})).toBeDisabled();await dialog.getByLabel('页面名称').fill('港口篇 · 备选');await dialog.getByRole('button',{name:'保存页面'}).click();await expect(page.getByRole('navigation',{name:'规划页面'})).toContainText('港口篇 · 备选');
 // Editing a stored note preserves style and catches a concurrent agent write.
 await page.getByRole('button',{name:'编辑批注 待讨论的动机',exact:true}).click();dialog=page.getByRole('dialog',{name:'文字批注',exact:true});await expect(dialog.getByLabel('字体',{exact:true})).toHaveValue('serif');await dialog.getByLabel('批注内容').fill('作者未保存的讨论');
 let latest=(await call('planning.decorations',{novelId,pageId})).items.find(d=>d.id===note.id);
 await call('planning.apply',{novelId,requestId:crypto.randomUUID(),operations:[{op:'decoration.update',id:note.id,expectedRevision:latest.revision,value:{content:'AI 补充了另一条疑问'}}]});
 await dialog.getByRole('button',{name:'保存批注'}).click();await expect(dialog.getByRole('alert')).toContainText('保存失败');await expect(dialog.getByLabel('批注内容')).toHaveValue('作者未保存的讨论');await dialog.locator('summary').filter({hasText:'比较最新批注'}).click();await expect(dialog.locator('pre')).toContainText('AI 补充了另一条疑问',{timeout:10000});
 await dialog.getByLabel('批注内容').fill('作者未保存的讨论\nAI 补充了另一条疑问');await dialog.getByRole('button',{name:'已合并，更新批注基准'}).click();await dialog.getByRole('button',{name:'保存批注',exact:true}).click();
 await expect(dialog).toHaveCount(0);await expect.poll(async()=>(await call('planning.decorations',{novelId,pageId})).items.find(d=>d.id===note.id).content).toBe('作者未保存的讨论\nAI 补充了另一条疑问');await expect(page.locator('.decoration-note')).toContainText('作者未保存的讨论');
 await page.setViewportSize({width:420,height:850});await context(390,380);const menu=await page.getByRole('menu',{name:'画布操作'}).boundingBox();expect(menu.x).toBeGreaterThanOrEqual(0);expect(menu.x+menu.width).toBeLessThanOrEqual(420);await page.screenshot({path:join(shots,'planning-context-narrow.png')});await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);
 await page.evaluate(()=>{document.documentElement.style.cssText='--dsw-alias-bg-base:#20251f;--dsw-alias-label-primary:#e4e8de;--dsw-alias-label-secondary:#a8b0a0;--dsw-alias-border-l1:#404a3b;--dsw-alias-state-success-primary:#a4c195';});await page.setViewportSize({width:1100,height:900});await page.screenshot({path:join(shots,'planning-page-dark.png')});
 await page.getByLabel('规划更多操作',{exact:true}).click();await page.getByRole('button',{name:'批量管理',exact:true}).click();await page.getByLabel('选择 抵达港口',{exact:true}).check();await page.getByLabel('移动到页面',{exact:true}).selectOption('');await page.getByRole('button',{name:'移动情节',exact:true}).click();
 await expect(page.locator('.planning-list .card')).toHaveCount(2);expect((await call('planning.list',{novelId,pageId})).total).toBe(0);expect((await call('planning.decorations',{novelId,pageId})).total).toBe(2);
 await page.getByRole('button',{name:'＋ 页面',exact:true}).click();dialog=page.getByRole('dialog',{name:'新建规划页面',exact:true});await dialog.getByLabel('页面名称').fill('临时页');await dialog.getByRole('button',{name:'保存页面'}).click();await page.getByRole('button',{name:'页面设置',exact:true}).click();await page.getByRole('dialog',{name:'页面设置',exact:true}).getByRole('button',{name:'删除空页面',exact:true}).click();
 await expect(page.getByRole('navigation',{name:'规划页面'})).not.toContainText('临时页');
 expect(errors).toEqual([]);console.log(JSON.stringify({ok:true,checks:['single manuscript keeps scroll across saves and remote sync','page creation/isolation/rename/reload','right-click scene, styled note, background frame','drag annotation and resize frame persist','annotation conflict retains author draft','narrow context menu and dark screenshots']}));
}catch(error){if(page)await page.screenshot({path:join(shots,'failure.png')}).catch(()=>{});throw error;}finally{await browser?.close();preview.kill();}
