// Real browser exercise of the shipped component against the production Store.
import { chromium, expect } from '@playwright/test';
import { build } from 'esbuild';
import { createServer } from 'node:http';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { Store } from '../src/core/store.js';
import { WorkData } from '../src/data/workspace.js';

const root = resolve(import.meta.dirname, '..');
const directory = await mkdtemp(join(tmpdir(), 'cuigengji-ui-'));
const store = new Store(directory);
const workData = new WorkData(store);
const actor = {kind:'human',sessionId:'ui-smoke'};
const novel = await store.dispatch('novel.create',{title:'浏览器测试小说'},actor);
await store.dispatch('binding.set',{novelId:novel.id},actor);
const chapter = await store.dispatch('chapter.create',{novelId:novel.id,title:'第一章',content:'门口有人敲门。'},actor);
await store.dispatch('binding.set',{novelId:novel.id,chapterId:chapter.id,goal:'接续门外的相遇'},actor);
const rpcActions=[];
  const output = await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{Workbench}from'./src/client/index.tsx';const rpc=async(action,args,sessionId)=>{const r=await fetch('/dispatch',{method:'POST',body:JSON.stringify({action,args,sessionId})});const value=await r.json();if(!r.ok)throw new Error(value.error);return value;};createRoot(document.getElementById('root')).render(<Workbench sessionId="ui-smoke" rpc={rpc}/>);`,resolveDir:root,loader:'tsx'},bundle:true,write:false,format:'iife',define:{'process.env.NODE_ENV':'"development"'}});
const server = createServer(async(req,res)=>{
  try {
    if(req.url==='/bundle.js'){res.setHeader('content-type','text/javascript');res.end(output.outputFiles[0].contents);return;}
    if(req.url==='/dispatch'){
      let body='';for await(const part of req)body+=part;
      const {action,args,sessionId}=JSON.parse(body);
      rpcActions.push(action);
      res.setHeader('content-type','application/json');
      const value=action.startsWith('workspace.')?await workData[{'workspace.status':'status','workspace.export':'export','workspace.preview':'preview','workspace.import':'import'}[action]](args.backup):await store.dispatch(action,args,{kind:'human',sessionId});
      res.end(JSON.stringify(value));return;
    }
    res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="zh"><meta charset="utf-8"><title>cuigengji UI smoke</title><style>html,body,#root{height:100%;margin:0}</style><body><div id="root"></div><script src="/bundle.js"></script></body></html>');
  }catch(e){res.statusCode=400;res.end(JSON.stringify({error:e.message}));}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;
try {
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:900,height:1000}});
  await mkdir(join(root,'test-results',process.env.UI_REVIEW || 'review'),{recursive:true});
  const capture=async name=>{for(const width of [900,420]){await page.setViewportSize({width,height:900});await page.waitForTimeout(150);await page.screenshot({path:join(root,'test-results',process.env.UI_REVIEW || 'review',`${name}-${width}.png`),fullPage:true});}await page.setViewportSize({width:900,height:1000});};
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await expect(page.locator('.chapter-item').filter({hasText:'第一章'})).toContainText('7 字');
  await page.getByRole('button',{name:/第一章/}).click();
  await capture('chapter');
  // A click in the button's padding also formats the whole chapter in the unified editor.
  await page.getByRole('button',{name:'自动排版',exact:true}).click({position:{x:5,y:5}});
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('　　门口有人敲门。');
  await page.getByRole('button',{name:'自动排版',exact:true}).click();
  await expect(page.getByText(/正文已是整齐|已排版：/)).toHaveCount(0);
  await page.getByRole('button',{name:'撤销排版',exact:true}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('门口有人敲门。');
  await expect(page.getByRole('button',{name:'设为 Agent 当前参考章节'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'查看 AI 参考'})).toHaveCount(0);
  await page.getByLabel('正文',{exact:true}).fill(' 第一段。  \n\n\n第二段。');
  await page.getByRole('button',{name:'自动排版',exact:true}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('　　第一段。\n\n　　第二段。');
  await expect.poll(async()=> (await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor)).content).toBe('　　第一段。\n\n　　第二段。');
  await page.getByRole('button',{name:'撤销排版',exact:true}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue(' 第一段。  \n\n\n第二段。');
  // Exercise the system clipboard and native paste, including a rich-text target.
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  const copiedProse='　　第一段：<正文> & "引号"。\n\n　　第二段。\n下一行。';
  const manuscript=page.getByLabel('正文',{exact:true});
  await manuscript.fill(copiedProse);
  await manuscript.press('ControlOrMeta+A');
  await manuscript.press('ControlOrMeta+C');
  const clipboardTypes=await page.evaluate(async()=> (await navigator.clipboard.read())[0].types);
  expect(clipboardTypes).toContain('text/plain');
  expect(clipboardTypes).toContain('text/html');
  await page.evaluate(()=>{
    const target=document.createElement('div');
    target.id='paste-review';target.contentEditable='true';
    target.setAttribute('aria-label','富文本粘贴测试');
    target.style.cssText='position:fixed;inset:30px;z-index:999;background:white;color:black;overflow:auto;';
    document.body.append(target);
  });
  const richTarget=page.getByLabel('富文本粘贴测试');
  await richTarget.focus();
  await richTarget.press('ControlOrMeta+V');
  await expect(richTarget.locator('p')).toHaveCount(4);
  expect(await richTarget.locator('p').allTextContents()).toEqual(copiedProse.split('\n'));
  await expect(richTarget.locator('正文')).toHaveCount(0);
  await richTarget.evaluate(el=>el.remove());
  await manuscript.fill('');
  await manuscript.press('ControlOrMeta+V');
  await expect(manuscript).toHaveValue(copiedProse);
  await manuscript.press('ControlOrMeta+Z');
  await expect(manuscript).toHaveValue('');
  await manuscript.fill(copiedProse);
  await manuscript.evaluate(el=>{el.focus();el.setSelectionRange(2,5);});
  await manuscript.press('ControlOrMeta+C');
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('第一段');
  await page.getByLabel('正文',{exact:true}).fill('门外站着一位陌生姑娘。');
  await expect(page.getByRole('button',{name:'保存修改',exact:true})).toHaveCount(0);
  await expect.poll(async()=> (await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor)).content).toBe('门外站着一位陌生姑娘。');
  await expect(page.locator('.chapter-item').filter({hasText:'第一章'})).toContainText('11 字');
  await page.getByLabel('正文',{exact:true}).fill('作者的未保存草稿。');
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('作者的未保存草稿。');
  await page.reload();
  await page.getByRole('button',{name:/第一章/}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('作者的未保存草稿。');
  await capture('chapter-editor');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByLabel('默认正文字号').selectOption('22');
  await page.getByLabel('正文行距',{exact:true}).selectOption('2.2');
  await capture('preferences');
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('作者的未保存草稿。');
  await expect(page.getByLabel('正文',{exact:true})).toHaveCSS('font-size','22px');
  await page.getByRole('button',{name:'关于催更姬',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'关于催更姬'})).toContainText('催更姬');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'关于催更姬',exact:true})).toBeFocused();

  await expect.poll(async()=> (await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor)).content).toBe('作者的未保存草稿。');
  const savedBeforeRemote=await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor);
  await store.dispatch('chapter.update',{novelId:novel.id,chapterId:chapter.id,expectedRevision:savedBeforeRemote.revision,content:'AI 更新后的正文。'},{kind:'agent',sessionId:actor.sessionId});
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('AI 更新后的正文。',{timeout:10000});
  await expect(page.getByText('你与 AI 或其他窗口修改了同一处，双方内容均已保留。')).toHaveCount(0);
  // A true concurrent edit stops autosaving and offers an explicit merge.
  const conflictBase=await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor);
  await page.getByLabel('正文',{exact:true}).fill('作者选择的走向。');
  await store.dispatch('chapter.update',{novelId:novel.id,chapterId:chapter.id,expectedRevision:conflictBase.revision,content:'AI 提出的另一走向。'},{kind:'agent',sessionId:actor.sessionId});
  await expect(page.getByRole('button',{name:'比较最新正文',exact:true})).toBeVisible({timeout:10000});
  await expect(page.getByLabel('正文',{exact:true})).toHaveValue('作者选择的走向。');
  await page.getByRole('button',{name:'比较最新正文',exact:true}).click();
  await expect(page.locator('.comparison')).toContainText('AI 提出的另一走向。');
  await page.getByLabel('合并正文',{exact:true}).fill('双方确认的合并走向。');
  await page.getByRole('button',{name:'已合并，更新保存基准',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}).click();
  await expect.poll(async()=> (await store.dispatch('chapter.get',{novelId:novel.id,chapterId:chapter.id},actor)).content).toBe('双方确认的合并走向。');

  await page.getByRole('button',{name:'设定',exact:true}).click();
  await page.locator('details.menu summary.primary').click();
  await page.locator('details.menu[open] .menu-panel button').filter({hasText:'角色卡'}).click();
  await page.locator('.creation').getByLabel('标题',{exact:true}).fill('夜班姑娘');
  await page.locator('.creation').getByLabel('摘要',{exact:false}).fill('住在隔壁的剑仙。');
  await page.locator('.creation').getByLabel('正文',{exact:false}).fill('她刚刚搬进这栋楼。');
  await capture('create-memory');
  await page.locator('.creation').getByRole('button',{name:'创建',exact:true}).click();
  await expect(page.getByRole('heading',{name:'夜班姑娘',exact:true})).toBeVisible();
  await capture('memory-detail');
  await page.getByRole('button',{name:'‹ 返回设定'}).click();
  await page.getByRole('button',{name:'＋ 新建分组',exact:true}).click();
  await page.getByRole('dialog',{name:'新建分组名称'}).getByLabel('输入值').fill('街坊');
  await page.getByRole('dialog',{name:'新建分组名称'}).getByRole('button',{name:'确定'}).click();
  await expect(page.getByLabel('设定分组')).toContainText('街坊');
  await capture('memory');
  // Settings creation, filters and relationship mutations use the real store.
  await page.locator('details.menu summary.primary').click();
  await page.getByRole('button',{name:'世界书',exact:true}).click();
  await page.locator('.creation').getByLabel('标题',{exact:true}).fill('城南书铺');
  await page.locator('.creation').getByLabel('正文',{exact:false}).fill('书铺的灯一直亮到午夜。');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('dialog',{name:'设置',exact:true}).getByText('规划默认视图').locator('select').selectOption('list');
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await expect(page.locator('.creation').getByLabel('正文',{exact:false})).toHaveValue('书铺的灯一直亮到午夜。');
  await page.locator('.creation').getByRole('button',{name:'创建',exact:true}).click();
  await page.getByRole('button',{name:'‹ 返回设定'}).click();
  await expect(page.locator('.library-entry')).toHaveCount(1);
  await page.getByRole('button',{name:'关系图',exact:true}).click();
  await expect(page.locator('.relation-canvas .planning-card')).toHaveCount(1);
  await page.getByRole('button',{name:'清除筛选',exact:true}).click();
  await expect(page.locator('.relation-canvas .planning-card')).toHaveCount(2);
  await page.getByRole('button',{name:'夜班姑娘：输出连接点',exact:true}).click();
  await page.keyboard.press('Escape');
  await expect(page.locator('.connect-source')).toHaveCount(0);
  await expect.poll(()=>store.dispatch('edge.list',{novelId:novel.id},actor)).toHaveLength(0);
  await page.getByRole('button',{name:'夜班姑娘：输出连接点',exact:true}).click();
  await page.getByRole('button',{name:'城南书铺：输入连接点',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'添加关系',exact:true})).toHaveCount(0);
  await expect(page.locator('.relation-canvas .edge-hit')).toHaveCount(1);
  await expect(page.locator('.relation-label')).toHaveCount(0);
  await page.locator('.relation-canvas .edge-hit').focus();await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'编辑关系',exact:true}).click();
  await page.getByLabel('关系名称（可选）',{exact:true}).fill('常去');
  await page.getByRole('dialog',{name:'编辑关系',exact:true}).getByLabel('说明',{exact:true}).fill('每天晚上在这里查阅旧书，追寻故乡旧友留下的线索，书页里或许藏着答案。');
  await page.getByRole('button',{name:'保存关系',exact:true}).click();
  await expect(page.locator('.relation-label')).toContainText('常去');
  await page.locator('.relation-label').getByRole('button',{name:'展开',exact:true}).click();
  await expect(page.locator('.relation-label')).toHaveClass(/expanded/);
  await page.locator('.relation-label').getByRole('button',{name:'收起',exact:true}).click();
  await capture('memory-relations');
  await page.getByLabel('类型',{exact:true}).selectOption('character_card');
  await expect(page.locator('.relation-canvas .planning-card')).toHaveCount(1);
  await expect(page.locator('.relation-label')).toHaveCount(0);
  await expect(page.locator('.relation-canvas .edge-hit')).toHaveCount(0);
  await page.getByRole('button',{name:'列表',exact:true}).click();
  await expect(page.locator('.library-entry')).toHaveCount(1);
  await page.getByLabel('搜索设定').fill('无匹配内容');
  await expect(page.getByText('没有匹配的设定，试试调整筛选。')).toBeVisible();
  await page.getByRole('button',{name:'清除筛选',exact:true}).click();
  await page.getByRole('button',{name:'关系图',exact:true}).click();
  await expect(page.locator('.relation-label')).toHaveCount(1);
  await page.locator('.relation-canvas .edge-hit').focus();await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'删除连线',exact:true}).click();
  await expect(page.locator('.relation-canvas .edge-hit')).toHaveCount(0);
  await expect.poll(()=>store.dispatch('edge.list',{novelId:novel.id},actor)).toHaveLength(0);

  await page.getByRole('button',{name:'规划',exact:true}).click();
  await expect(page.getByRole('button',{name:'列表',exact:true})).toHaveAttribute('aria-pressed','true');
  for(const title of ['敲门','邻居现身']){
    await page.getByRole('button',{name:'＋ 规划'}).click();
    await page.locator('.creation').getByLabel('标题',{exact:true}).fill(title);
    await page.locator('.creation').getByRole('button',{name:'创建',exact:true}).click();
    await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
    if(title==='敲门')await capture('planning-detail');
    await page.getByRole('button',{name:'‹ 返回规划'}).click();
  }
  if(await page.getByRole('button',{name:'流程图'}).count())await page.getByRole('button',{name:'流程图'}).click();
  await expect(page.locator('.planning-card')).toHaveCount(2);
  await expect(page.getByLabel('画布关系类型')).toHaveCount(0);
  await page.getByRole('button',{name:'敲门：输出连接点',exact:true}).click();
  await page.keyboard.press('Escape');
  await expect(page.locator('.planning-card.connect-source')).toHaveCount(0);
  await expect(page.locator('.edge-hit')).toHaveCount(0);
  await page.getByRole('button',{name:'敲门：输出连接点',exact:true}).click();
  await expect(page.locator('.planning-card.connect-source')).toHaveCount(1);
  await page.getByRole('button',{name:'邻居现身：输入连接点',exact:true}).click();
  await expect(page.locator('.edge-hit')).toHaveCount(1);
  const edgePoint=await page.getByRole('button',{name:'连线：敲门 → 邻居现身',exact:true}).evaluate(path=>{const point=path.getPointAtLength(path.getTotalLength()/2);const screen=new DOMPoint(point.x,point.y).matrixTransform(path.getScreenCTM());return {x:screen.x,y:screen.y};});
  await page.mouse.click(edgePoint.x,edgePoint.y);
  await page.getByRole('button',{name:'删除连线',exact:true}).click();
  await expect(page.locator('.edge-hit')).toHaveCount(0);
  await page.getByRole('button',{name:'敲门：输出连接点',exact:true}).click();
  await page.getByRole('button',{name:'邻居现身：输入连接点',exact:true}).click();
  await expect(page.locator('.edge-hit')).toHaveCount(1);
  const card=page.locator('.planning-card').filter({hasText:'敲门'});
  const box=await card.boundingBox();
  await page.mouse.move(box.x+80,box.y+85);
  await page.mouse.down();
  await page.mouse.move(box.x+113,box.y+105,{steps:5});
  await page.mouse.up();
  await expect.poll(async()=>store.dispatch('planning.get',{novelId:novel.id,nodeId:(await store.dispatch('planning.list',{novelId:novel.id},actor)).items.find(n=>n.title==='敲门').id},actor).then(result=>result.node.position?.x)).toBeGreaterThan(32);
  await page.getByRole('button',{name:'＋ 新建分组',exact:true}).click();
  await page.getByRole('dialog',{name:'新建分组名称'}).getByLabel('输入值').fill('第一幕');
  await page.getByRole('dialog',{name:'新建分组名称'}).getByRole('button',{name:'确定'}).click();
  await expect(page.getByLabel('规划分组')).toContainText('第一幕');
  await expect(page.getByText('没有匹配的规划，试试调整筛选。')).toBeVisible();
  await page.getByRole('button',{name:'清除筛选',exact:true}).click();
  await mkdir(join(root,'test-results'),{recursive:true});
  await page.screenshot({path:join(root,'test-results','planning-desktop.png'),fullPage:true});
  await capture('planning');
  await expect(page.getByRole('button',{name:'AI 参考',exact:true})).toHaveCount(0);
  await expect(page.locator('.reference-drawer')).toHaveCount(0);
  if(rpcActions.includes('context.get'))throw new Error('UI must not fetch agent prose context');
  await page.getByLabel('作品操作',{exact:true}).click();
  await page.getByRole('button',{name:'写作预设',exact:true}).click();
  await expect(page.getByRole('heading',{name:'写作预设',exact:true})).toBeVisible();
  await capture('preset');
  await page.getByText(/当前草稿的生效文本预览/).click();
  await expect(page.getByText('保存并启用后，这些文本会在下次请求时加入当前作品绑定会话的系统提示词。酒馆的触发、角色与装填规则不执行，宏保留为原文。',{exact:true})).toBeVisible();
  await page.getByLabel('作品操作',{exact:true}).click();
  await page.getByRole('button',{name:'工作数据 · 导入/导出',exact:true}).click();
  await expect(page.getByRole('heading',{name:'小说工作数据',exact:true})).toBeVisible();
  await expect(page.getByText(directory,{exact:true})).toBeVisible();
  await capture('work-data');
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出全部工作数据',exact:true}).click();
  const download=await downloadEvent;
  await page.getByLabel('导入工作数据',{exact:true}).setInputFiles(await download.path());
  await expect(page.getByRole('heading',{name:'导入预览',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'确认导入',exact:true}).click();
  await expect(page.getByText(/导入完成。导入前备份/)).toBeVisible();
  await page.screenshot({path:join(root,'test-results','work-data-narrow.png'),fullPage:true});
  await page.getByLabel('作品操作',{exact:true}).click();
  await page.getByRole('button',{name:'作品与备份',exact:true}).click();
  await capture('manage');
  await page.getByRole('button',{name:'规划',exact:true}).click();
  await page.getByRole('button',{name:'流程图',exact:true}).click();
  await page.locator('.planning-card').filter({hasText:'邻居现身'}).getByRole('button',{name:'邻居现身',exact:true}).click();
  await page.getByRole('button',{name:'＋ 接着推进',exact:true}).click();
  await page.locator('.creation').getByLabel('标题',{exact:true}).fill('邀请邻居进屋');
  await page.locator('.creation').getByRole('button',{name:'创建',exact:true}).click();
  await expect(page.getByRole('heading',{name:'邀请邻居进屋',exact:true})).toBeVisible();
  await expect(page.getByLabel('情节前后关系')).toContainText('邻居现身');
  await capture('planning-flow-detail');
  await page.getByRole('button',{name:'‹ 返回上一条',exact:true}).click();
  await expect(page.getByRole('heading',{name:'邻居现身',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'‹ 返回规划',exact:true}).click();
  await expect(page.locator('.planning-card')).toHaveCount(3);
  await expect(page.locator('.edge-hit')).toHaveCount(2);
  await capture('planning-flow');

  await page.getByRole('button',{name:'正文',exact:true}).click();
  await page.getByRole('button',{name:'＋ 章节',exact:true}).click();
  await page.locator('.creation').getByLabel('标题',{exact:true}).fill('未完成章节');
  await page.locator('.creation').getByLabel('正文',{exact:false}).fill('原先写下的草稿。');
  await page.getByRole('button',{name:'＋ 新建卷',exact:true}).click();
  await page.getByRole('dialog',{name:'新卷名称',exact:true}).getByLabel('输入值').fill('第二卷');
  await page.getByRole('dialog',{name:'新卷名称',exact:true}).getByRole('button',{name:'确定',exact:true}).click();
  await expect(page.locator('.creation').getByLabel('正文',{exact:false})).toHaveValue('原先写下的草稿。');
  await capture('create-chapter');
  await page.locator('.creation').getByRole('button',{name:'‹ 取消',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}).click();
  expect((await store.dispatch('chapter.list',{novelId:novel.id},actor)).map(c=>c.title)).not.toContain('未完成章节');

  if(process.env.NOVEL_REVIEW){
    // Import a snapshot into the disposable test store, never the author's live data.
    const backup=JSON.parse(await readFile(process.env.NOVEL_REVIEW,'utf8'));
    await store.dispatch('novel.import',{backup},actor);
    await page.getByLabel('作品操作',{exact:true}).click();
    await page.getByRole('button',{name:'刷新作品',exact:true}).click();
    await page.getByLabel('绑定小说',{exact:true}).selectOption(backup.novel.id);
    await expect(page.locator('.chapter-item').first()).toBeVisible();
    await capture('novel-directory');
    await page.locator('.chapter-item').first().click();
    await capture('novel-reading');
      await capture('novel-editing');
    await page.getByLabel('正文',{exact:true}).focus();
    const editorStyle=await page.getByLabel('正文',{exact:true}).evaluate(el=>({border:getComputedStyle(el).borderWidth,outline:getComputedStyle(el).outlineStyle,overflow:getComputedStyle(el).overflowY,scroll:el.scrollHeight,height:el.clientHeight}));
    expect(editorStyle.border).toBe('0px');expect(editorStyle.outline).toBe('none');expect(editorStyle.overflow).toBe('hidden');expect(editorStyle.scroll).toBeLessThanOrEqual(editorStyle.height+2);

    // Collapse on desktop, then return to the directory in a narrow panel.
    await page.getByRole('button',{name:'收起章节目录',exact:true}).click();
    await page.setViewportSize({width:360,height:800});
    await page.getByRole('button',{name:'‹ 目录',exact:true}).click();
    await expect(page.getByRole('dialog',{name:'章节目录抽屉'})).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('button',{name:'‹ 目录',exact:true})).toBeFocused();
    await page.getByRole('button',{name:'‹ 目录',exact:true}).click();
    await expect(page.locator('.chapter-item').first()).toBeVisible();
    await page.locator('.chapter-item').first().click();
    await page.getByRole('button',{name:'自动排版',exact:true}).click({position:{x:5,y:5}});
    await expect(page.getByLabel('正文',{exact:true})).toBeVisible();
    if(await page.locator('.editor-heading').evaluate(el=>el.scrollWidth>el.clientWidth+1))throw new Error('chapter toolbar overflows narrow panel');
    await page.screenshot({path:join(root,'test-results',process.env.UI_REVIEW||'review','novel-360.png'),fullPage:true});
  }
  await page.setViewportSize({width:1280,height:900});
  await page.getByLabel('绑定小说',{exact:true}).selectOption(novel.id);
  await page.getByRole('button',{name:'设定',exact:true}).click();
  await expect(page.locator('.library-entry')).toHaveCount(2);
  await page.evaluate(()=>{document.documentElement.style.cssText='--dsw-alias-bg-base:#20251f;--dsw-alias-bg-layer-1:#2a3029;--dsw-alias-label-primary:#e4e8de;--dsw-alias-label-secondary:#a8b0a0;--dsw-alias-border-l1:#404a3b;--dsw-alias-state-success-primary:#a4c195;--dsw-alias-label-on-color:#182313';});
  await expect(page.locator('.cuigengji').first()).toHaveCSS('color','rgb(228, 232, 222)');
  await page.locator('.library-entry').first().click();
  await expect(page.locator('.document-body')).toBeVisible();
  await page.waitForTimeout(180);
  await page.screenshot({path:join(root,'test-results',process.env.UI_REVIEW||'review','dark-wide.png'),fullPage:true});
  await page.getByRole('button',{name:'‹ 返回设定',exact:true}).click();
  await page.setViewportSize({width:360,height:800});
  expect(await page.locator('.module-heading').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
  await page.screenshot({path:join(root,'test-results',process.env.UI_REVIEW||'review','dark-360.png'),fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  console.log(JSON.stringify({ok:true,checks:['automatic chapter save and clean remote sync','rich-text clipboard','connected plot continuation','chapter edit','draft survives reload','settings creation, group/type/search and real relation CRUD','planning nodes, edge, persisted position and group','no reference drawer or format notices','preset navigation','work-data export and import'],dataDir:directory}));
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
