import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {Store} from '../src/core/store.js';
import {WorkData} from '../src/data/workspace.js';
const checksum=b=>{b.sha256=createHash('sha256').update(JSON.stringify(b.payload)).digest('hex');return b;};
async function setup(t){const root=await mkdtemp(join(tmpdir(),'cuigengji-data-'));t.after(()=>rm(root,{recursive:true,force:true}));const source=new Store(join(root,'source')),target=new Store(join(root,'target'));const actor={kind:'human',sessionId:'author'};const n=await source.dispatch('novel.create',{title:'工作数据测试作品'},actor);await source.dispatch('binding.set',{novelId:n.id},actor);const c=await source.dispatch('chapter.create',{title:'第一章',content:'原稿'},actor);await source.dispatch('chapter.update',{chapterId:c.id,expectedRevision:c.revision,content:'修改后的正文'},actor);await mkdir(join(source.root,'audit'));await writeFile(join(source.root,'audit','a'.repeat(64)+'.jsonl'),'test audit\n');return {source,target,actor,n,from:new WorkData(source),to:new WorkData(target)};}
test('whole work data roundtrip keeps prose versions, binding and audit, and preserves target books',async t=>{const {source,target,actor,n,from,to}=await setup(t);await target.dispatch('novel.create',{title:'桌面原有作品'},actor);const backup=await from.export();assert.equal((await to.preview(backup)).valid,true);const report=await to.import(backup);assert.equal(report.added.length,1);const a=await source.load(),b=await target.load();assert.deepEqual(b.novels[n.id],a.novels[n.id]);assert.deepEqual(b.bindings,a.bindings);assert.equal(Object.keys(b.novels).length,2);assert.equal(await readFile(join(target.root,'audit','a'.repeat(64)+'.jsonl'),'utf8'),'test audit\n');assert.equal((await to.preview(backup)).skipped.length,1);assert.ok(JSON.parse(await readFile(join(report.backupDir,'workspace.json'),'utf8')).state);});
test('tampered and path traversal archives reject before changing target',async t=>{const {target,from,to}=await setup(t);const before=await target.load(),backup=await from.export();backup.payload.files[0].path='../escape.json';await assert.rejects(to.import(backup),/校验/);checksum(backup);await assert.rejects(to.import(backup),/路径/);assert.deepEqual(await target.load(),before);});
test('conflict after preview is checked again on import; no partial novels are added',async t=>{const {target,actor,n,from,to}=await setup(t);const backup=await from.export();assert.equal((await to.preview(backup)).valid,true);await target.dispatch('novel.import',{backup:{format:'cuigengji',schemaVersion:2,novel:backup.payload.state.novels[n.id]}},actor);await target.dispatch('novel.update',{novelId:n.id,expectedRevision:backup.payload.state.novels[n.id].revision,title:'本地新版本'},actor);const before=await target.load();await assert.rejects(to.import(backup),/冲突/);assert.deepEqual(await target.load(),before);});
