import React,{useState} from 'react';
import {useDialog} from '../../dialog.tsx';
export function Manage({call,novelId,novel,run,busy,onOpen}) {
 const [mode,setMode]=useState(''),[preview,setPreview]=useState(null),[report,setReport]=useState(null),[success,setSuccess]=useState(''),[importedId,setImportedId]=useState(null);
 const {ask}=useDialog();
 const reset=()=>{setMode('');setPreview(null);setReport(null);};
 const choose=next=>{setMode(next);setPreview(null);setReport(null);setSuccess('');setImportedId(null);};
 const read=event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setPreview(null);setReport(null);setSuccess('');setImportedId(null);run(async()=>{const input=JSON.parse((await file.text()).replace(/^\uFEFF/,''));if(mode==='legacy'){const result=await call('legacy.preview',{input});setPreview(result.backup);setReport(result.report);}else{if(input.format!=='cuigengji'||!input.novel)throw new Error('不是支持的插件备份');setPreview(input);}});};
 const download=()=>run(async()=>{const data=await call('novel.export',{novelId});const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${novel?.title||'novel'}.cuigengji.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSuccess('已生成并触发下载，请在浏览器下载列表确认。');});
 return <><h2>{mode?(mode==='backup'?'恢复插件备份':'迁移旧项目'):'作品与备份'}</h2>{!mode?<>
  {novelId&&<section className="section-fold"><div className="row"><strong className="grow">{novel?.title}</strong><button disabled={busy} onClick={async()=>{const title=await ask('作品名称',novel?.title||'');if(title?.trim())run(async()=>{const current=await call('novel.get',{novelId});await call('novel.update',{novelId,title,expectedRevision:current.revision});});}}>重命名</button></div><p className="muted">完整备份包含正文、历史、设定、规划和预设。</p><button className="primary" disabled={busy} onClick={download}>下载完整备份</button></section>}
  <div className="list action-list"><button disabled={busy} onClick={()=>choose('backup')}><strong>恢复插件备份</strong><span>从本插件导出的 JSON 恢复作品</span></button><button disabled={busy} onClick={()=>choose('legacy')}><strong>迁移旧项目</strong><span>预览旧项目内容与兼容报告</span></button></div>
 </>:<><button disabled={busy} onClick={reset}>‹ 返回管理</button><p className="muted">{mode==='backup'?'选择插件备份，检查作品内容后导入。':'选择包含正文的旧项目 JSON，核对迁移报告后导入。'}</p><label>选择文件<input disabled={busy} type="file" accept=".json,application/json" onChange={read}/></label>
 {report&&<details className="section-fold" open><summary>迁移报告</summary><p>{report.volumes} 卷 · {report.chapters} 章 · {report.nodes} 个设定 · {report.edges} 条关系</p>{report.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 {preview&&<section className="section-fold"><h3>{preview.novel.title}</h3><p>{Object.keys(preview.novel.chapters||{}).length} 章 · {Object.keys(preview.novel.nodes||{}).length} 个设定 · {Object.keys(preview.novel.planning?.nodes||{}).length} 个规划节点</p><p className="muted">新增作品；相同内容跳过。同 ID 内容不同会拒绝导入，原作品不被覆盖。</p><div className="row"><button className="primary" disabled={busy} onClick={()=>run(async()=>{const result=await call('novel.import',{backup:preview});setImportedId(result.id);setSuccess(result.imported?'导入完成。':'作品已存在，未重复导入。');setPreview(null);setReport(null);})}>确认导入</button><button disabled={busy} onClick={()=>{setPreview(null);setReport(null);}}>取消</button></div></section>}
 </>}{success&&<div className="notice" role="status">{success}{importedId&&<button disabled={busy} onClick={()=>onOpen?.(importedId)}>打开作品</button>}</div>}</>;
}
