import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';

const root=resolve(import.meta.dirname,'..');
const file=join(root,'design/2026-09-29/prototype.html');
const server=createServer(async(req,res)=>{
  if(req.url!=='/'&&req.url!=='/prototype.html'){res.writeHead(404);res.end();return;}
  try{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile(file));}
  catch{res.writeHead(500);res.end('Unable to read design prototype');}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
console.log(url);
if(process.argv.includes('--check')){
 const {chromium,expect}=await import('@playwright/test');
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1200,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const output=join(root,'test-results/visual-proposal');await mkdir(output,{recursive:true});
  await page.goto(url);
  const shot=async name=>{await page.waitForTimeout(190);await page.screenshot({path:join(output,`${name}.png`),fullPage:true});};
  await expect(page.locator('.prototype-caption')).toHaveCount(0);
  await expect(page.getByText('安静的写作工作台',{exact:false})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'设置',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'关于催更姬',exact:true})).toBeVisible();
  await expect(page.locator('.node')).toHaveCount(4);await shot('planning-wide');
  await expect(page.locator('.canvas-scope .group-new')).toBeVisible();
  await expect(page.locator('.menu [data-menu="groups"]')).toHaveCount(0);
  await page.getByRole('button',{name:'新建分组',exact:false}).click();
  await expect(page.getByRole('dialog').getByLabel('分组名称')).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
  await expect(page.getByRole('button',{name:'设定',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'资料',exact:true})).toHaveCount(0);
  const planningCard=await page.locator('.node').first().evaluate(el=>({width:el.getBoundingClientRect().width,titleFont:getComputedStyle(el.querySelector('h3')).fontSize}));
  await page.getByRole('button',{name:'列表',exact:true}).click();
  await expect(page.locator('.entry')).toHaveCount(4);
  await expect(page.locator('.library-heading .group-new')).toBeVisible();
  await expect(page.getByLabel('选择分组')).toHaveValue('雨夜来信');
  await shot('planning-list-wide');
  await page.locator('.entry[data-open="follow"]').click();
  await page.getByRole('button',{name:'返回列表',exact:false}).click();
  await expect(page.getByRole('button',{name:'列表',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.setViewportSize({width:420,height:900});await shot('planning-list-narrow');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1200,height:900});
  await page.getByRole('button',{name:'流程图',exact:true}).click();
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await page.locator('.search-input').fill('暗中跟踪');
  await expect(page.locator('.node:visible')).toHaveCount(1);
  await page.locator('.search-input').fill('');
  await expect(page.locator('.node:visible')).toHaveCount(4);
  await page.getByRole('button',{name:'关闭搜索',exact:true}).click();
  await page.locator('.node[data-open="follow"]').click();await expect(page.locator('.detail h1')).toHaveText('暗中跟踪');await shot('planning-detail-wide');
  await page.getByRole('button',{name:'编辑',exact:true}).click();
  await page.locator('#edit-title').fill('悄悄跟踪');await page.getByRole('button',{name:'保存',exact:true}).click();
  await expect(page.locator('.detail h1')).toHaveText('悄悄跟踪');
  await page.getByRole('button',{name:'设定',exact:true}).click();
  await expect(page.locator('.library-heading .group-new')).toBeVisible();
  await page.getByLabel('设定分组',{exact:true}).selectOption('group:城中人物');
  await expect(page.locator('.entry:visible')).toHaveCount(2);
  await page.getByLabel('设定类型',{exact:true}).selectOption('世界设定');
  await expect(page.locator('.entry:visible')).toHaveCount(0);
  await expect(page.locator('[data-scope-empty]')).toBeVisible();
  await page.getByLabel('设定类型',{exact:true}).selectOption('人物');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await page.getByLabel('搜索内容',{exact:true}).fill('沈砚');
  await expect(page.locator('.entry:visible')).toHaveCount(1);
  await expect(page.locator('[data-result-count]')).toHaveText('1 条设定');
  await shot('settings-filtered-list-wide');
  await page.getByRole('button',{name:'关系图',exact:true}).click();
  await expect(page.getByLabel('设定分组',{exact:true})).toHaveValue('group:城中人物');
  await expect(page.getByLabel('设定类型',{exact:true})).toHaveValue('人物');
  await expect(page.getByLabel('搜索内容',{exact:true})).toHaveValue('沈砚');
  await expect(page.locator('.memory-graph .node:visible')).toHaveCount(1);
  await expect(page.locator('.relation-label:visible')).toHaveCount(0);
  await page.getByRole('button',{name:'关闭搜索',exact:true}).click();
  await page.getByLabel('设定分组',{exact:true}).selectOption('group:地点与风俗');
  await page.getByLabel('设定类型',{exact:true}).selectOption('世界设定');
  await page.setViewportSize({width:360,height:800});await shot('settings-filtered-graph-narrow');
  await expect(page.locator('.memory-graph .node:visible')).toHaveCount(2);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const visibleWorld=await page.locator('.node[data-open="world"]').boundingBox();
  expect(visibleWorld.x).toBeGreaterThanOrEqual(0);expect(visibleWorld.x+visibleWorld.width).toBeLessThanOrEqual(360);
  await page.getByRole('button',{name:'列表',exact:true}).click();await shot('settings-filtered-list-narrow');
  await page.getByLabel('设定分组',{exact:true}).selectOption('ungrouped');
  await expect(page.locator('[data-scope-empty]')).toBeVisible();
  await page.getByRole('button',{name:'新建分组',exact:false}).click();
  await page.getByRole('dialog').getByLabel('分组名称').fill('皇城');
  await page.getByRole('dialog').getByRole('button',{name:'创建分组',exact:true}).click();
  await expect(page.getByLabel('设定分组',{exact:true})).toHaveValue('group:皇城');
  await page.getByRole('button',{name:'新设定',exact:true}).click();
  await expect(page.locator('#create-group')).toHaveValue('皇城');
  await page.getByRole('button',{name:'角色卡',exact:true}).click();
  await expect(page.locator('#create-group')).toHaveValue('皇城');
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByRole('button',{name:'清除筛选',exact:true}).click();
  await expect(page.getByLabel('设定分组',{exact:true})).toHaveValue('all');
  await expect(page.getByLabel('设定类型',{exact:true})).toHaveValue('全部');
  await page.setViewportSize({width:1200,height:900});
  await page.getByRole('button',{name:'关系图',exact:true}).click();
  await expect(page.locator('.canvas-scope .group-new')).toBeVisible();
  await expect(page.locator('.memory-graph .node')).toHaveCount(4);
  expect(await page.locator('.memory-graph .node').first().evaluate(el=>({width:el.getBoundingClientRect().width,titleFont:getComputedStyle(el.querySelector('h3')).fontSize}))).toEqual(planningCard);
  await expect(page.locator('[data-memory-edge]')).toHaveCount(4);
  await expect(page.locator('.relation-label')).toHaveCount(3);
  await expect(page.locator('[data-relation-label="manages"]')).toHaveText('经营');
  await expect(page.locator('[data-relation-label="clue"]')).toHaveText('曾将书铺的钥匙留给沈砚。');
  await expect(page.locator('[data-relation-label="unlabelled"]')).toHaveCount(0);
  expect(await page.locator('[data-memory-edge="unlabelled"]').evaluate(el=>getComputedStyle(el).display!=='none'&&parseFloat(getComputedStyle(el).strokeWidth)>0&&el.getTotalLength()>0)).toBe(true);
  await shot('memory-relations-wide');
  expect(await page.evaluate(()=>{
    const cards=[...document.querySelectorAll('.memory-graph .node')].map(el=>el.getBoundingClientRect());
    return [...document.querySelectorAll('.relation-label')].every(el=>{const r=el.getBoundingClientRect();return cards.every(c=>r.right<=c.left||r.left>=c.right||r.bottom<=c.top||r.top>=c.bottom);});
  })).toBe(true);
  await page.locator('.memory-graph .node[data-open="character"]').click();
  await expect(page.locator('.detail h1')).toHaveText('沈砚');
  await expect(page.locator('.detail .relation-label')).toHaveCount(0);await shot('memory-relations-detail');
  await page.getByRole('button',{name:'返回设定',exact:false}).click();
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await page.locator('.search-input').fill('南街');
  await expect(page.locator('[data-memory-edge="manages"]')).not.toBeVisible();
  await expect(page.locator('[data-relation-label="manages"]')).not.toBeVisible();
  await page.getByRole('button',{name:'关闭搜索',exact:true}).click();
  await page.setViewportSize({width:420,height:900});await shot('memory-relations-narrow');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'缩小',exact:true}).click();
  await expect(page.locator('.canvas-tools span')).toHaveText('90%');
  await page.getByRole('button',{name:'放大',exact:true}).click();
  await page.setViewportSize({width:1200,height:900});
  await page.evaluate(()=>{memoryRelations.find(e=>e.id==='clue').content='七年前，他把书铺钥匙留给了沈砚。'+ '这件事与来信之间的联系仍需要进一步讨论。'.repeat(5);render();});
  await page.locator('[data-relation-label="clue"] summary').focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('[data-relation-label="clue"] details')).toHaveAttribute('open','');
  expect(await page.locator('[data-relation-label="clue"]').evaluate(el=>el.getBoundingClientRect().height<=141)).toBe(true);
  await page.evaluate(()=>{memoryRelations.find(e=>e.id==='clue').content='曾将书铺的钥匙留给沈砚。';render();});
  await page.getByRole('button',{name:'列表',exact:true}).click();
  await page.locator('.entry[data-open="character"]').click();await shot('character-wide');
  await page.setViewportSize({width:420,height:900});await shot('character-narrow');
  await page.getByRole('button',{name:'南街旧书铺',exact:false}).click();await shot('world-narrow');
  await page.getByRole('button',{name:'编辑',exact:true}).click();await shot('world-editing-narrow');
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByRole('button',{name:'规划',exact:true}).click();await shot('planning-narrow');
  await page.locator('.node[data-open="letter"]').click();await shot('planning-detail-narrow');
  await page.getByRole('button',{name:'接着推进',exact:false}).click();
  await expect(page.locator('.creation-context')).toContainText('雨夜来信');
  await shot('new-plot-narrow');
  await page.getByRole('button',{name:'创建情节',exact:true}).click();
  await expect(page.locator('#create-error')).toBeVisible();
  await page.getByLabel('情节标题',{exact:true}).fill('新的示例情节');
  await page.locator('#create-summary').fill('走出书铺，寻找送信的少年。');
  await page.getByRole('button',{name:'创建情节',exact:true}).click();
  await expect(page.locator('.detail h1')).toHaveText('新的示例情节');
  await page.getByRole('button',{name:'返回流程图',exact:false}).click();
  await expect(page.locator('.node')).toHaveCount(5);
  await expect(page.locator('[data-edge-from="letter"]')).toHaveCount(3);
  await page.getByRole('button',{name:'新情节',exact:true}).click();
  await page.getByLabel('情节标题',{exact:true}).fill('取消的情节');
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await expect(page.locator('.node')).toHaveCount(5);
  await page.setViewportSize({width:360,height:800});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'正文',exact:true}).click();await shot('manuscript-narrow');
  await page.getByRole('button',{name:'展开章节目录',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();await shot('directory-narrow');
  await expect(page.getByRole('dialog').locator('.chapter-count').first()).toContainText('字');
  await page.getByRole('dialog').getByLabel('新建目录内容').click();
  await page.getByRole('button',{name:'新建分卷',exact:true}).click();await shot('new-volume-narrow');
  await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
  await expect(page.getByRole('dialog').getByLabel('章节目录')).toBeVisible();
  await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.locator('.directory-trigger')).toBeFocused();
  await page.getByRole('button',{name:'展开章节目录',exact:true}).click();
  await page.getByRole('dialog').getByLabel('新建目录内容').click();
  await page.getByRole('button',{name:'新建章节',exact:true}).click();
  await shot('new-chapter-narrow');
  await page.getByLabel('章节标题',{exact:true}).fill('第四章 重逢');
  await page.getByRole('button',{name:'新建分卷',exact:false}).click();
  await page.getByRole('dialog').getByLabel('分卷名称').fill('第三卷 · 重逢');
  await page.getByRole('dialog').getByRole('button',{name:'创建分卷',exact:true}).click();
  await expect(page.locator('#create-title')).toHaveValue('第四章 重逢');
  await expect(page.locator('#create-group option:checked')).toHaveText('第三卷 · 重逢');
  await page.getByRole('button',{name:'创建章节',exact:true}).click();
  await expect(page.getByLabel('示例正文')).toHaveValue('');
  await page.getByLabel('示例正文').fill('天地\n\n　　人间！');
  await expect(page.locator('[data-current-count]')).toHaveText('5 字');
  await page.getByRole('button',{name:'自动排版',exact:true}).click();
  await expect(page.getByLabel('示例正文')).toHaveValue('　　天地\n\n　　人间！');
  await page.setViewportSize({width:1200,height:900});
  await page.getByRole('button',{name:'完成',exact:true}).click();
  await expect(page.locator('.chapter.active .chapter-count')).toHaveText('5 字');
  await shot('directory-wide');
  await page.getByRole('button',{name:'收起章节目录',exact:true}).click();
  await expect(page.locator('.manuscript-shell>.directory')).toHaveCount(0);await shot('directory-collapsed-wide');
  await page.getByRole('button',{name:'展开章节目录',exact:true}).click();
  const volume=page.locator('.volume-toggle').filter({hasText:'第一卷'});
  await volume.click();await expect(volume).toHaveAttribute('aria-expanded','false');
  await volume.click();await expect(volume).toHaveAttribute('aria-expanded','true');
  await page.getByRole('button',{name:'设定',exact:true}).click();
  await page.getByRole('button',{name:'新设定',exact:true}).click();
  await shot('new-character-wide');
  await page.getByRole('button',{name:'世界书',exact:true}).click();
  await page.getByLabel('条目名称',{exact:true}).fill('渡口的规矩');
  await page.locator('#create-summary').fill('入夜以后，渡船只接熟人。');
  await page.locator('#create-body').fill('船家认的是信物，\n不是来人的脸。');
  await shot('new-world-wide');
  await page.setViewportSize({width:420,height:900});await shot('new-world-narrow');
  await page.getByRole('button',{name:'新建分组',exact:false}).click();await shot('new-group-narrow');
  await page.getByRole('dialog').getByLabel('分组名称').fill('河岸与渡口');
  await page.getByRole('dialog').getByRole('button',{name:'创建分组',exact:true}).click();
  await expect(page.locator('#create-title')).toHaveValue('渡口的规矩');
  await page.getByRole('button',{name:'创建条目',exact:true}).click();
  await expect(page.locator('.detail h1')).toHaveText('渡口的规矩');
  await expect(page.locator('.detail .kicker')).toContainText('河岸与渡口');
  await expect(page.locator('.document-body')).toContainText('船家认的是信物');
  await page.getByRole('button',{name:'规划',exact:true}).click();
  await page.getByRole('button',{name:'新情节',exact:true}).click();
  await page.getByLabel('情节标题',{exact:true}).fill('渡口相遇');
  await page.getByRole('button',{name:'新建分组',exact:false}).click();
  await page.getByRole('dialog').getByLabel('分组名称').fill('渡口支线');
  await page.getByRole('dialog').getByRole('button',{name:'创建分组',exact:true}).click();
  await page.getByRole('button',{name:'创建情节',exact:true}).click();
  await page.getByRole('button',{name:'返回流程图',exact:false}).click();
  await expect(page.getByLabel('选择分组')).toHaveValue('渡口支线');
  await expect(page.locator('.node:visible')).toHaveCount(1);
  await page.setViewportSize({width:360,height:800});
  await page.getByRole('button',{name:'新情节',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'设定',exact:true}).click();
  await page.getByLabel('设定分组',{exact:true}).selectOption('all');
  await page.locator('.entry[data-open="character"]').click();
  expect(await page.locator('.detail').evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:1200,height:900});
  await page.getByRole('button',{name:'编辑',exact:true}).click();
  await page.locator('#edit-title').fill('尚未保存的人物草稿');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'设置',exact:true})).toBeVisible();await shot('preferences-wide');
  await page.getByLabel('正文字号',{exact:true}).selectOption('22');
  await page.getByLabel('段落行距',{exact:true}).selectOption('2.2');
  expect(await page.locator('.reading-preview p').evaluate(el=>getComputedStyle(el).fontSize)).toBe('22px');
  await page.getByLabel('默认展开章节目录',{exact:true}).uncheck();
  await page.getByLabel('规划默认视图',{exact:true}).selectOption('list');
  await page.getByLabel('设定默认视图',{exact:true}).selectOption('graph');
  await page.getByLabel('动态效果',{exact:true}).selectOption('reduce');
  await expect(page.locator('[data-preference-status]')).toHaveText('偏好已保存在此浏览器');
  await page.setViewportSize({width:360,height:800});await shot('preferences-narrow');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'恢复默认',exact:true}).scrollIntoViewIfNeeded();
  await expect(page.getByRole('button',{name:'关闭设置',exact:true})).toBeVisible();
  await shot('preferences-narrow-bottom');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'设置',exact:true})).toBeFocused();
  await expect(page.locator('#edit-title')).toHaveValue('尚未保存的人物草稿');
  await page.getByRole('button',{name:'关于催更姬',exact:true}).click();await shot('about-narrow');
  await expect(page.getByRole('dialog',{name:'关于催更姬',exact:true})).toContainText('不连接正式作品');
  await page.getByRole('button',{name:'关闭关于催更姬',exact:true}).click();
  await page.setViewportSize({width:1200,height:900});
  await page.reload();
  await expect(page.getByRole('button',{name:'列表',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'设定',exact:true}).click();
  await expect(page.getByRole('button',{name:'关系图',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.locator('.node[data-open="character"]').click();
  expect(await page.locator('.detail').evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
  await page.getByRole('button',{name:'正文',exact:true}).click();
  await expect(page.locator('.manuscript-shell>.directory')).toHaveCount(0);
  expect(await page.locator('.manuscript-view p').first().evaluate(el=>getComputedStyle(el).fontSize)).toBe('22px');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('button',{name:'恢复默认',exact:true}).click();
  await expect(page.getByLabel('正文字号',{exact:true})).toHaveValue('18');
  await expect(page.getByLabel('默认展开章节目录',{exact:true})).toBeChecked();
  await page.getByRole('button',{name:'关闭设置',exact:true}).click();
  await page.getByRole('button',{name:'关于催更姬',exact:true}).click();await shot('about-wide');
  await page.getByRole('button',{name:'关闭关于催更姬',exact:true}).click();
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ok:true,checks:['flow navigation','optional inline relation labels, no placeholder or card overlap','memory graph navigation, filtering and zoom','shared detail for plot/character/world','in-place edit/save','continuation without empty nodes on cancel','collapsible directory and volumes','live chapter counts','drawer keyboard dismissal','chapter/volume/character/world/plot/group creation','360px fit','reduced motion','styled group/type filters','removed top caption','settings preview, persistence, defaults and draft preservation','about dialog and narrow dialog scrolling'],screenshots:output}));
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
}
