import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
export interface MenuItem {label:string;action?:()=>void;children?:MenuItem[];danger?:boolean;disabled?:boolean}
export function CanvasMenu({x,y,close,items}:{x:number;y:number;close:()=>void;items:MenuItem[]}){
 const ref=useRef<HTMLDivElement>(null),[submenu,setSubmenu]=useState<MenuItem|null>(null),[position,setPosition]=useState({left:x,top:y});
 const shown=submenu?.children||items;
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;const rect=el.getBoundingClientRect();setPosition({left:Math.max(8,Math.min(x,window.innerWidth-rect.width-8)),top:Math.max(8,Math.min(y,window.innerHeight-rect.height-8))});el.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();},[x,y,submenu]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))close();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();}};window.addEventListener('pointerdown',outside);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',outside);window.removeEventListener('keydown',key);};},[]);
 return <div ref={ref} role="menu" aria-label="画布操作" className="graph-context-menu" style={position} onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=[...ref.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')],index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}}}>{submenu&&<button role="menuitem" onClick={()=>setSubmenu(null)}>‹ {submenu.label}</button>}{shown.map(item=><button role="menuitem" className={item.danger?'danger':''} disabled={item.disabled} key={item.label} onClick={()=>{if(item.children)setSubmenu(item);else{close();item.action?.();}}}>{item.label}{item.children&&<span aria-hidden="true">›</span>}</button>)}</div>;
}
