import React,{useEffect,useRef,useState} from 'react';
import {Modal} from '../../shared/preferences.tsx';
import type {Decoration,Point} from '../../../contracts/planning.ts';
export type DecorationDraft=Omit<Decoration,'id'|'revision'|'deleted'>&{id?:string;revision?:number};
export function newDecoration(kind:'note'|'frame',position:Point,pageId:string|null):DecorationDraft{return {kind,pageId,position,title:kind==='frame'?'讨论区域':'',content:'',width:kind==='frame'?560:280,height:kind==='frame'?360:180,color:kind==='frame'?'sage':'sand',fontSize:18,fontFamily:'sans'};}
const colors={neutral:'灰',sand:'米黄',sage:'浅绿',sky:'浅蓝',rose:'浅粉'};
export function DecorationEditor({initial,latest,busy,save,remove,close}:{initial:DecorationDraft;latest?:Decoration;busy:boolean;save:(value:DecorationDraft)=>Promise<boolean|undefined>;remove:(value:DecorationDraft)=>Promise<boolean|undefined>;close:()=>void}){
  const [draft,setDraft]=useState(initial),[base,setBase]=useState(initial),[error,setError]=useState('');
  const field=(key:string,value:unknown)=>setDraft(old=>({...old,[key]:value}));
  return <Modal title={draft.kind==='frame'?'背景框':'文字批注'} close={close}><form className="editor-fields decoration-editor" onSubmit={async e=>{e.preventDefault();if(await save(draft))close();else setError('保存失败，内容仍在这里，请核对版本后重试。');}}>
    <label>标题<input autoFocus value={draft.title} onChange={e=>field('title',e.target.value)}/></label><label>批注内容<textarea rows={5} value={draft.content} onChange={e=>field('content',e.target.value)} placeholder="疑问、备选方向，或这一片区域的讨论重点"/></label>
    <div className="decoration-options"><label>底色<select value={draft.color} onChange={e=>field('color',e.target.value)}>{Object.entries(colors).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>字体<select aria-label="字体" value={draft.fontFamily} onChange={e=>field('fontFamily',e.target.value)}><option value="sans">黑体</option><option value="serif">宋体</option></select></label><label>字号<select aria-label="字号" value={draft.fontSize} onChange={e=>field('fontSize',Number(e.target.value))}>{[14,18,24,32].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
    <div className="decoration-options"><label>宽度<input type="number" min={160} max={6000} value={draft.width} onChange={e=>field('width',Number(e.target.value))}/></label><label>高度<input type="number" min={80} max={6000} value={draft.height} onChange={e=>field('height',Number(e.target.value))}/></label></div>
    {error&&<p role="alert">{error}</p>}{latest&&latest.revision!==base.revision&&<details className="section-fold"><summary>比较最新批注 · 本地草稿仍保留</summary><strong>{latest.title}</strong><pre>{latest.content}</pre><p>在上方合并需要的内容，再更新保存基准。</p><button type="button" disabled={busy} onClick={()=>{const changed=Object.fromEntries(Object.entries(draft).filter(([key,value])=>!['id','revision'].includes(key)&&JSON.stringify(value)!==JSON.stringify(base[key as keyof DecorationDraft])));setDraft({...latest,...changed});setBase(latest);setError('');}}>已合并，更新批注基准</button></details>}<div className="row"><button type="submit" className="primary" disabled={busy}>保存批注</button>{draft.id&&<button type="button" disabled={busy} onClick={async()=>{if(await remove(draft))close();else setError('删除未完成，批注仍保留。');}}>删除批注</button>}</div>
  </form></Modal>;
}
export function DecorationCard({value,point,zoom,busy,dragProps,edit,resize}:{value:Decoration;point:Point;zoom:number;busy:boolean;dragProps:React.HTMLAttributes<HTMLElement>;edit:()=>void;resize:(value:Decoration,size:{width:number;height:number})=>Promise<boolean|undefined>}){
  const [size,setSize]=useState({width:value.width,height:value.height});
  const gesture=useRef<{x:number;y:number;width:number;height:number;pointer:number;value:Decoration;size:{width:number;height:number}}|null>(null);
  const cancel=()=>{const g=gesture.current;if(g)setSize({width:g.width,height:g.height});gesture.current=null;};
  useEffect(()=>{if(!gesture.current)setSize({width:value.width,height:value.height});},[value.width,value.height]);
  useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();};window.addEventListener('keydown',escape);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',escape);window.removeEventListener('blur',cancel);};},[]);
  return <section data-decoration-id={value.id} className={`planning-decoration decoration-${value.kind} tone-${value.color}`} style={{left:point.x,top:point.y,...size,fontSize:value.fontSize,fontFamily:value.fontFamily==='serif'?'"Noto Serif SC","SimSun",serif':'inherit'}}>
    <header data-graph-drag="true" {...dragProps}><button className="decoration-title" aria-label={`编辑批注 ${value.title||'未命名批注'}`}>{value.title||'讨论批注'}</button><span aria-hidden="true">⠿</span></header>
    <div className="decoration-content" onDoubleClick={edit}>{value.content}</div>
    <button className="decoration-resize" aria-label={`调整批注尺寸 ${value.title||'未命名批注'}`} title="拖动调整大小；也可在编辑中输入尺寸" disabled={busy} onClick={e=>e.stopPropagation()} onPointerDown={e=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();gesture.current={x:e.clientX,y:e.clientY,width:size.width,height:size.height,pointer:e.pointerId,value,size};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;e.stopPropagation();g.size={width:Math.max(160,Math.min(6000,g.width+(e.clientX-g.x)/zoom)),height:Math.max(80,Math.min(6000,g.height+(e.clientY-g.y)/zoom))};setSize(g.size);}} onPointerCancel={cancel} onPointerUp={async e=>{const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;e.stopPropagation();gesture.current=null;if(g.size.width===g.width&&g.size.height===g.height)return;if(!await resize(g.value,g.size))setSize({width:value.width,height:value.height});}}>◢</button>
  </section>;
}
