import React,{useState} from 'react';
import {Modal} from '../../shared/preferences.tsx';
export interface PageIndex {id:string|null;name:string;summary:string;revision:number;nodeCount:number;decorationCount:number}
interface Props {pages:PageIndex[];value:string;busy:boolean;change:(id:string)=>void;create:(name:string,summary:string)=>Promise<boolean|undefined>;update:(page:PageIndex,name:string,summary:string)=>Promise<boolean|undefined>;remove:(page:PageIndex)=>Promise<boolean|undefined>}
export function PlanningPages({pages,value,busy,change,create,update,remove}:Props){
  const [draft,setDraft]=useState<{page?:PageIndex;name:string;summary:string}|null>(null),[error,setError]=useState('');
  const current=pages.find(p=>(p.id||'')===value);
  return <><nav className="planning-pages" aria-label="规划页面"><div className="page-tabs">{pages.map(p=><button key={p.id||'main'} aria-current={(p.id||'')===value?'page':undefined} onClick={()=>change(p.id||'')} title={p.summary}>{p.name}<small>{p.nodeCount}</small></button>)}</div><button className="add-page" disabled={busy} onClick={()=>{setError('');setDraft({name:'',summary:''});}}>＋ 页面</button>{current?.id&&<button aria-label="页面设置" onClick={()=>{setError('');setDraft({page:current,name:current.name,summary:current.summary});}}>···</button>}</nav>
  {draft&&<Modal title={draft.page?'页面设置':'新建规划页面'} close={()=>setDraft(null)}><form className="editor-fields" onSubmit={async e=>{e.preventDefault();const ok=draft.page?await update(draft.page,draft.name,draft.summary):await create(draft.name,draft.summary);if(ok)setDraft(null);else setError('未保存，请核对提示后重试。');}}><label>页面名称<input autoFocus required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>用途摘要<textarea placeholder="这页讨论哪段情节，方便你和 AI 找到它" value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<div className="row"><button type="submit" className="primary" disabled={busy||!draft.name.trim()}>保存页面</button>{draft.page&&<button type="button" disabled={busy||draft.page.nodeCount>0||draft.page.decorationCount>0} title="只删除空页面；有内容时请先移动情节并删除批注" onClick={async()=>{if(await remove(draft.page!))setDraft(null);else setError('未删除，请核对页面是否仍有内容。');}}>删除空页面</button>}</div></form></Modal>}
  </>;
}
