import React,{useEffect,useState,useRef} from 'react';
import {useResource,useDraft,usePreference} from '../shared/state.js';
import {ResourceState,SaveBar,saveShortcut} from '../shared/ui.jsx';
import {useDialog} from '../dialog.jsx';
import {ChapterEvidence} from '../shared/evidence.jsx';
import {readPlanningSnapshot} from './data.js';
import {PlanningCanvas} from './Canvas.jsx';
const statusNames={idea:'构想',selected:'准备采用',written:'已写入正文',dropped:'放弃'};
const scopeNames={long:'长期',phase:'阶段',near:'近期',unspecified:'未指定'};
const edgeNames={next:'剧情推进',requires:'依赖铺垫',alternative:'备选分支'};
export function Planning({call,novelId,tick,run,busy,onChapter,onMemory}) {
 const [parent,setParent]=usePreference(`${novelId}:planning-parent`,null),[selected,setSelected]=usePreference(`${novelId}:planning-selected`,null),[viewChoice,setView]=usePreference(`${novelId}:planning-view`,'auto'),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[thread,setThread]=useState(''),[poll,setPoll]=useState(0),[historyOpen,setHistoryOpen]=useState(false),[changes,setChanges]=useState(null);
 const panel=useRef(null),[panelWidth,setPanelWidth]=useState(480);
 useEffect(()=>{const observer=new ResizeObserver(entries=>setPanelWidth(entries[0].contentRect.width));if(panel.current)observer.observe(panel.current);return()=>observer.disconnect();},[]);
 const view=viewChoice==='auto'?(panelWidth<760?'list':'canvas'):viewChoice;
 const {ask,confirm}=useDialog();
 const resource=useResource(()=>readPlanningSnapshot(call,novelId),[call,novelId,tick,poll]);
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)setPoll(n=>n+1);},4000);return()=>clearInterval(timer);},[]);
 const nodes=resource.value?.items||[],edges=resource.value?.edges||[];
 const [seen,setSeen]=usePreference(`${novelId}:planning-seen`,0);
 const sequence=resource.value?.sequence||0;
 const transact=(operations,reason)=>run(()=>call('planning.apply',{novelId,requestId:crypto.randomUUID(),operations,reason,...(operations.some(op=>op.op==='node.delete')?{expectedSequence:sequence}:{})}));
 const add=async()=>{const title=await ask('规划标题');if(title?.trim())run(async()=>{const result=await call('planning.apply',{novelId,requestId:crypto.randomUUID(),reason:'新增规划',operations:[{op:'node.create',ref:'new',value:{title,parentId:parent,scope:parent?'near':'long'}}]});setSelected(result.mapping.new);});};
 const visible=nodes.filter(n=>(query?`${n.title} ${n.summary} ${n.threads.join(' ')}`.toLowerCase().includes(query.toLowerCase()):n.parentId===parent)&&(!filter||n.status===filter)&&(!thread||n.threads.includes(thread)));
 const openHistory=()=>run(async()=>{let result=await call('planning.history',{novelId,offset:0,limit:200});setChanges(result);setHistoryOpen(true);});
 const chain=[];let current=nodes.find(n=>n.id===parent);const walked=new Set();while(current&&!walked.has(current.id)){walked.add(current.id);chain.unshift(current);current=nodes.find(n=>n.id===current.parentId);}
 return <div ref={panel} className={`planning-workspace ${selected?'has-detail':''}`}>
  <header className="module-heading"><div className="row"><h2 className="grow">故事规划</h2><button disabled={busy} onClick={openHistory}>{sequence>seen?'有新变化 · ':''}修改记录</button><button className="primary" disabled={busy} onClick={add}>＋ 规划</button></div>
   <div className="row breadcrumbs"><button onClick={()=>{setParent(null);setSelected(null);}}>全书</button>{chain.map(n=><button key={n.id} onClick={()=>{setParent(n.id);setSelected(null);}}>› {n.title}</button>)}</div>
   <div className="row"><input className="grow" aria-label="搜索规划" placeholder="搜索规划标题、概述、故事线" value={query} onChange={e=>setQuery(e.target.value)}/><details className="menu"><summary>筛选{filter||thread?' · 已启用':''}</summary><div className="menu-panel"><label>进展<select aria-label="规划状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部状态</option>{Object.entries(statusNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>故事线<select aria-label="故事线" value={thread} onChange={e=>setThread(e.target.value)}><option value="">全部故事线</option>{[...new Set(nodes.flatMap(n=>n.threads))].sort().map(t=><option key={t} value={t}>{t}</option>)}</select></label><button onClick={()=>{setFilter('');setThread('');}}>清除筛选</button></div></details><button onClick={()=>setView(view==='canvas'?'list':'canvas')}>{view==='canvas'?'列表视图':'流程图'}</button></div>
  </header>
  <ResourceState resource={resource}><div className="planning-columns">
   <aside className="planning-directory"><strong>规划目录</strong><Directory nodes={nodes} parentId={null} selected={selected} choose={n=>{setParent(n.parentId);setSelected(n.id);}}/></aside><div className="planning-overview">{!visible.length?<div className="empty">{query||filter||thread?'没有匹配的规划':'这一层还没有规划。添加一个方向，再逐步拆成场景。'}</div>:view==='canvas'?<PlanningCanvas key={parent||'root'} nodes={visible} childCounts={Object.fromEntries(nodes.map(n=>[n.id,nodes.filter(c=>c.parentId===n.id).length]))} edges={edges} novelId={novelId} layer={parent} seen={seen} selected={selected} onSelect={setSelected} onEnter={id=>{setParent(id);setSelected(null);setQuery('');}}/>:<div className="planning-list">{visible.map(n=><div className="card" key={n.id}><button className="planning-title" onClick={()=>setSelected(n.id)}>{n.title}</button><span className="status-badge">{statusNames[n.status]}</span><p>{n.summary}</p>{nodes.some(c=>c.parentId===n.id)&&<button onClick={()=>{setParent(n.id);setSelected(null);setQuery('');}}>子规划 · {nodes.filter(c=>c.parentId===n.id).length}</button>}</div>)}</div>}</div>
   {selected&&<div className="planning-detail"><button onClick={()=>setSelected(null)}>‹ 返回规划</button><PlanningDetail key={selected} {...{call,novelId,run,busy,nodes,edges,transact,onChapter,onMemory}} onEnter={()=>{setParent(selected);setSelected(null);setQuery('');}} id={selected} latest={nodes.find(n=>n.id===selected)} close={()=>setSelected(null)}/></div>}
  </div></ResourceState>
  {historyOpen&&<div className="planning-history page"><div className="row"><h2 className="grow">规划修改记录</h2><button onClick={()=>setSeen(changes?.sequence||sequence)}>标为已读</button><button onClick={()=>setHistoryOpen(false)}>关闭记录</button></div>{changes?.items.map(t=><details className="card" key={t.id}><summary>{t.actor.kind==='agent'?'AI':'作者'} · {t.reason} · {new Date(t.updatedAt).toLocaleString()} · {t.changes.length} 项</summary>{t.changes.map(c=><div key={`${c.collection}:${c.id}`}><h3>{c.after.title||edgeNames[c.after.type]||'关系'}</h3><p className="muted">{changeSummary(c)}</p><details><summary>比较前后版本</summary><div className="split"><div><h4>修改前</h4><pre>{describe(c.before,nodes)}</pre></div><div><h4>修改后</h4><pre>{describe(c.after,nodes)}</pre></div></div></details>{c.collection==='nodes'&&!c.after.deleted&&<button onClick={()=>{setParent(nodes.find(n=>n.id===c.id)?.parentId||null);setSelected(c.id);setHistoryOpen(false);}}>定位节点</button>}</div>)}<button disabled={busy} onClick={async()=>{if(await confirm('撤销这次变更？若相关对象已有后续修改，将拒绝覆盖。'))run(async()=>{await call('planning.revert',{novelId,transactionId:t.id,requestId:crypto.randomUUID()});setHistoryOpen(false);});}}>撤销这次变更</button></details>)}{changes?.nextOffset!==null&&<button disabled={busy} onClick={()=>run(async()=>{const next=await call('planning.history',{novelId,offset:changes.nextOffset,limit:200});setChanges({...next,items:[...changes.items,...next.items]});})}>加载更多记录</button>}</div>}
 </div>;
}
function PlanningDetail(props){const resource=useResource(()=>props.call('planning.get',{novelId:props.novelId,nodeId:props.id}),[props.call,props.novelId,props.id]);return <ResourceState resource={resource}>{resource.value&&<PlanningEditor {...props} initial={resource.value.node}/>}</ResourceState>;}
function PlanningEditor({call,novelId,run,busy,id,initial,latest,nodes,edges,transact,close,onChapter,onMemory,onEnter}){
 const {value,base,change,accept,rebase,dirty,cacheError}=useDraft(`${novelId}:planning:${id}`,initial);const {confirm,ask}=useDialog();
 const refs=useResource(()=>Promise.all([call('chapter.list',{novelId}),call('graph.list',{novelId})]),[call,novelId]);const [chapters=[],memory=[]]=refs.value||[];
 const [target,setTarget]=useState(''),[edgeType,setEdgeType]=useState('next'),[referenceQuery,setReferenceQuery]=useState(''),[remote,setRemote]=useState(null),[editing,setEditing]=useState(dirty||(initial.revision===1&&!initial.content));
 const [threadText,setThreadText]=useState(value.threads.join(', '));
 useEffect(()=>setThreadText(value.threads.join(', ')),[base]);
 const set=(key,v)=>change(old=>({...old,[key]:v}));
 const reload=()=>run(async()=>accept((await call('planning.get',{novelId,nodeId:id})).node));
 const save=()=>run(async()=>{await call('planning.apply',{novelId,requestId:crypto.randomUUID(),reason:`修改 ${value.title}`,operations:[{op:'node.update',id,expectedRevision:base.revision,value}]});accept((await call('planning.get',{novelId,nodeId:id})).node);});
 return <div onKeyDown={e=>saveShortcut(e,()=>{if(dirty&&!busy)save();})}><div className="row"><h2 className="grow">{value.title}</h2><button onClick={()=>setEditing(!editing)}>{editing?'阅读预览':'编辑规划'}</button></div>{latest?.revision!==base.revision&&<p className="notice">远端有更新，草稿仍保留。保存会检查版本。</p>}{value.deleted&&<p className="notice">此规划已删除，可在历史中撤销删除。</p>}
 {editing?<fieldset className="editor-fields" disabled={busy||value.deleted}><label>标题<input value={value.title} onChange={e=>set('title',e.target.value)}/></label><div className="split"><label>范围<select value={value.scope} onChange={e=>set('scope',e.target.value)}>{Object.entries(scopeNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>进展<select value={value.status} onChange={e=>set('status',e.target.value)}>{Object.entries(statusNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>卡片概述<textarea value={value.summary} onChange={e=>set('summary',e.target.value)}/></label><label>详细规划<textarea className="prose" value={value.content} onChange={e=>set('content',e.target.value)}/></label><label>所属阶段<select value={value.parentId||''} onChange={e=>set('parentId',e.target.value||null)}><option value="">全书</option>{nodes.filter(n=>n.id!==id).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>故事线（逗号分隔）<input value={threadText} onChange={e=>{setThreadText(e.target.value);set('threads',[...new Set(e.target.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean))]);}}/></label>
 <details><summary>关联正文与人物设定</summary>{value.chapterRefs.map(r=><p key={r.chapterId}>{chapters.find(c=>c.id===r.chapterId)?.title||'已删除或缺失章节'} · 版本{r.revision}<button onClick={()=>set('chapterRefs',value.chapterRefs.filter(x=>x.chapterId!==r.chapterId))}>移除</button></p>)}{value.memoryRefs.map(id=><p key={id}>{memory.find(n=>n.id===id)?.name||'已删除或缺失设定'}<button onClick={()=>set('memoryRefs',value.memoryRefs.filter(x=>x!==id))}>移除</button></p>)}<input aria-label="筛选关联资料" placeholder="搜索章节或设定" value={referenceQuery} onChange={e=>setReferenceQuery(e.target.value)}/>{chapters.filter(c=>c.title.includes(referenceQuery)).map(c=><label className="row" key={c.id}><input type="checkbox" checked={value.chapterRefs.some(r=>r.chapterId===c.id)} onChange={e=>set('chapterRefs',e.target.checked?[...value.chapterRefs,{chapterId:c.id,revision:c.revision}]:value.chapterRefs.filter(r=>r.chapterId!==c.id))}/>{c.title}<button type="button" onClick={()=>onChapter(c.id)}>打开</button>{value.chapterRefs.some(r=>r.chapterId===c.id&&r.revision!==c.revision)&&<span>正文版本已变化</span>}</label>)}{memory.filter(n=>n.name.includes(referenceQuery)).map(n=><label className="row" key={n.id}><input type="checkbox" checked={value.memoryRefs.includes(n.id)} onChange={e=>set('memoryRefs',e.target.checked?[...value.memoryRefs,n.id]:value.memoryRefs.filter(v=>v!==n.id))}/>{n.name}</label>)}</details>
 </fieldset>:<section className="planning-reading"><p className="muted">{scopeNames[value.scope]} · {statusNames[value.status]} · {value.threads.join(' / ')||'未指定故事线'}</p><p>{value.summary}</p><pre>{value.content||'尚未填写详细规划'}</pre>{value.chapterRefs.map(r=><ChapterEvidence key={r.chapterId} {...{call,novelId,onChapter}} source={r} title={chapters.find(c=>c.id===r.chapterId)?.title}/>)}{value.memoryRefs.map(ref=><p key={ref}><button onClick={()=>onMemory(ref)}>{memory.find(n=>n.id===ref)?.name||'已删除或缺失设定'}</button></p>)}</section>}{(editing||dirty)&&<SaveBar {...{dirty,busy}} error={cacheError} invalid={!value.title.trim()?'请填写标题':value.deleted?'已删除':null} onSave={save} label="保存规划"/>}
 <div className="row"><button onClick={()=>run(()=>navigator.clipboard.writeText(`规划：${value.title} [规划节点: ${id}]`))}>复制节点引用</button><button disabled={busy} onClick={async()=>{if(!dirty||await confirm('丢弃本地草稿并读取最新规划？'))reload();}}>读取最新</button></div>
 <button disabled={busy} onClick={()=>run(async()=>setRemote((await call('planning.get',{novelId,nodeId:id})).node))}>比较远端版本</button>
 {remote&&<section className="card"><h3>远端版本 {remote.revision}</h3><div className="split"><div><h3>本地</h3><pre>{describe(value,nodes)}</pre></div><div><h3>远端</h3><pre>{describe(remote,nodes)}</pre></div></div><p>在上方编辑器合并需要的内容，再更新保存基准。</p><button disabled={busy||remote.deleted} onClick={async()=>{if(await confirm('确认已合并需要的内容？后续保存仍检查版本。')){rebase(remote);setRemote(null);}}}>已合并，更新保存基准</button><button onClick={()=>setRemote(null)}>关闭比较</button></section>}
 <button onClick={onEnter}>查看或添加子规划</button><details className="section-fold"><summary>剧情关系</summary>{edges.filter(e=>e.from===id||e.to===id).map(e=><div key={e.id} className="source-row">{nodes.find(n=>n.id===e.from)?.title} → {edgeNames[e.type]} → {nodes.find(n=>n.id===e.to)?.title}<button disabled={busy} onClick={async()=>{if(await confirm('删除这条规划关系？'))transact([{op:'edge.delete',id:e.id,expectedRevision:e.revision,confirm:true}],'删除规划关系');}}>移除</button></div>)}
 <div className="row"><select aria-label="关系类型" value={edgeType} onChange={e=>setEdgeType(e.target.value)}>{Object.entries(edgeNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="目标规划" value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择目标</option>{nodes.filter(n=>n.id!==id).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select><button disabled={busy||!target} onClick={()=>transact([{op:'edge.create',value:{from:id,to:target,type:edgeType}}],'建立剧情关系')}>连接</button></div>
 </details><details><summary>删除规划</summary><button className="danger" disabled={busy} onClick={async()=>{let childPolicy='detach';if(nodes.some(n=>n.parentId===id)){const choice=await ask('输入“移出”保留子节点，或“子树”删除全部下级','移出');if(!['移出','子树'].includes(choice))return;childPolicy=choice==='子树'?'subtree':'detach';}if(await confirm('删除此规划及相关连线？可在修改记录中撤销。')){const ok=await transact([{op:'node.delete',id,expectedRevision:base.revision,confirm:true,childPolicy}],'删除规划');if(ok){accept(initial);close();}}}}>删除节点</button></details>
 </div>;
}

function Directory({nodes,parentId,selected,choose}) {
 return nodes.filter(n=>n.parentId===parentId).map(n=>nodes.some(c=>c.parentId===n.id)?<details key={n.id} open={undefined}><summary>{n.title}</summary><button aria-current={selected===n.id?'true':undefined} onClick={()=>choose(n)}>查看此规划</button><div className="planning-branch"><Directory {...{nodes,selected,choose}} parentId={n.id}/></div></details>:<button key={n.id} aria-current={selected===n.id?'true':undefined} onClick={()=>choose(n)}>{n.title}</button>);
}
function describe(value,nodes) {
 if(!value)return '不存在（本次新增）';
 if(value.from)return `${nodes.find(n=>n.id===value.from)?.title||value.from} → ${edgeNames[value.type]} → ${nodes.find(n=>n.id===value.to)?.title||value.to}\n${value.label||''}${value.deleted?'\n已删除':''}`;
 return [`标题：${value.title}`,`范围：${scopeNames[value.scope]} · 进展：${statusNames[value.status]}`,`所属：${nodes.find(n=>n.id===value.parentId)?.title||value.parentId||'全书'}`,`故事线：${value.threads.join('、')||'未指定'}`,`概述：${value.summary}`,value.content,`正文引用：${value.chapterRefs.map(r=>`${r.chapterId} · 版本${r.revision}`).join('；')||'无'}`,`设定引用：${value.memoryRefs.join('、')||'无'}`,value.deleted?'已删除':''].filter(Boolean).join('\n');
}

function changeSummary(change) {
 if(!change.before)return '新增';
 const labels={title:'标题',summary:'概述',content:'详细内容',scope:'范围',status:'进展',parentId:'所属阶段',threads:'故事线',chapterRefs:'正文引用',memoryRefs:'设定引用',deleted:'删除状态',from:'起点',to:'终点',type:'关系类型',label:'关系说明'};
 return Object.entries(labels).filter(([key])=>JSON.stringify(change.before[key])!==JSON.stringify(change.after[key])).map(([,label])=>label).join('、')||'版本更新';
}
